### ISSUE TITLE
Hessian-vector product from stan-dev/math

### ISSUE THREAD

**Issue by bob-carpenter** [roualdes/bridgestan#125] opened 2023-05-26 15:50 UTC
Expose the version of the Hessian-vector product functional from [`stan-dev/math`](https://github.com/stan-dev/math).

Here's the functional we need to expose.  We want the first one that uses reverse-mode nested in forward mode):

https://github.com/stan-dev/math/blob/develop/stan/math/mix/functor/hessian_times_vector.hpp

We should use the first version in the file (reverse nested in forward), because it's linear.  Doing it with finite diffs and multiply will be quadratic (as will be using the second version in the source file).

The motivation is the optimizer (conjugate gradient trust region method) used by the following paper, which uses [`trust-ncg`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustncg.html) in `scipi.optimize.minimize`:

https://arxiv.org/pdf/2304.05527.pdf

@rgiordan said that they used PyMC because it provided Hessian-vector products.

**Comment by WardBrian** [comment] 2023-05-26 15:59
I think this is a duplicate of (part of) #84

**Closed** 2023-09-14 02:05 UTC
Labels: enhancement
